title: Aetherial Arts
description:  Mythic storytelling • Visual intelligence • Immersive world-building
theme: minima

# github repo
repository: aetherialarts/aetherialarts.github.io

# Use the newer Minima version + custom skin
minima:
  social_links:
    - { platform: github, url: "https://github.com/aetherialarts" }

# Author:
#author: "Aetherial Arts"

# Enable future expansion:
markdown: kramdown

plugins:
  - jekyll-feed
